language: groovy
jdk: oraclejdk7
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
script: gradle build
install: 
- chmod +x gradle
- gradle setupCIworkspace
- travis setup releases